; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
extra_scripts = pre:tools/example_select.py

[platformio]
description = ClusterDuck Protocol Library
lib_dir = ./src
extra_configs = src/config/*.ini

[esp32_base]
extends = cdp_common
platform = espressif32
board = esp32dev
framework = arduino
build_flags = ${cdp_common.build_flags}

[arduino_base]
extends = cdp_common
framework = arduino
lib_deps = 
	${env.lib_deps}
	https://github.com/end2endzone/NonBlockingRTTTL/archive/refs/tags/1.4.0.zip
build_unflags = 
	-std=c++11
	-std=gnu++11
build_flags = ${env.build_flags} -Os
	-std=gnu++17
build_src_filter = ${env.build_src_filter} -<platform/> +<platform/extra_variants/> -<graphics/niche/>

[nrf52_base]
platform = 
	platformio/nordicnrf52@10.12.0
extends = arduino_base
platform_packages = 
	platformio/framework-arduinoadafruitnrf52 @ https://github.com/meshtastic/Adafruit_nRF52_Arduino#0fd295f13203e93df19d578073646ec32f2bf45a
	platformio/toolchain-gccarmnoneeabi@~1.90301.0
build_type = release
build_flags = 
	${cdp_common.build_flags}
	-Wno-unused-variable
	-Isrc/platform/nrf52
	-DLOOP_STACK_SZ=2048
	-Os
	-std=gnu++17
	-flto
	-fmerge-all-constants
build_unflags = 
	-Ofast
	-Og
	-ggdb3
	-ggdb2
	-g3
	-g2
	-g
	-g1
	-g0
	-std=c++11
	-std=gnu++11
build_src_filter = 
	${arduino_base.build_src_filter} +<platform/nrf52/> -<nimble/> -<mesh/wifi/> -<mesh/api/> -<mesh/http/> -<modules/esp32> -<mesh/eth/> -<mesh/raspihttp> -<serialization/>
lib_deps = 
	${arduino_base.lib_deps}
	https://github.com/meshtastic/Crypto/archive/591ff9a690e8168ccb7a36abde8d7783e448d395.zip
lib_ignore = 
	BluetoothOTA
	lvgl

[nrf52840_base]
extends = nrf52_base
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v6.ld
build_flags = 
	${nrf52_base.build_flags}
	-DSERIAL_BUFFER_SIZE=4096
	-DLED_BUILTIN=-1
lib_deps = 
	${nrf52_base.lib_deps}
	https://github.com/Kongduino/Adafruit_nRFCrypto/archive/8cde7189b5ead9dcd49f72601b43b969c0bbc06e.zip
debug_init_break = tbreak setup
debug_extra_cmds = 
	echo Running .gdbinit script
	commands 1
	set useSoftDevice = 0
	end
debug_load_mode = modified
debug_tool = stlink
debug_speed = 4000

[env:release_cdp]
extends = esp32_base
lib_deps = 
	${cdp_common.lib_deps}
	https://github.com/muhammadn/ClusterDuck-Protocol#feature/as923-radio
	https://github.com/ropg/heltec_esp32_lora_v3/archive/refs/tags/v0.9.2.zip
	h2zero/NimBLE-Arduino@^2.1.0
	nanopb/Nanopb@^0.4.91

[env:local_cdp]
extends = esp32_base
lib_deps = 
	${cdp_common.lib_deps}
	symlink://./
	nanopb/Nanopb@^0.4.91

[env:prod_heltec_wifi_lora_32_V2]
extends = env:release_cdp
board = heltec_wifi_lora_32_V2
lib_deps = nanopb/Nanopb@^0.4.91

[env:prod_heltec_wifi_lora_32_V3]
extends = env:release_cdp
board = heltec_wifi_lora_32_V3
lib_deps = nanopb/Nanopb@^0.4.91

[env:prod_heltec_wifi_lora_32_V4]
extends = env:release_cdp
board = heltec_wifi_lora_32_V3
build_flags = 
	${cdp_common.build_flags}
	-DARDUINO_heltec_wifi_lora_32_V4
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
lib_deps = 
	${env:release_cdp.lib_deps}
	mikalhart/TinyGPSPlus
	nanopb/Nanopb@^0.4.91

[env:prod_lilygo_t_beam_sx1262]
extends = env:release_cdp
board = ttgo-t-beam
lib_deps = nanopb/Nanopb@^0.4.91

[env:prod_lilygo_t_beam_sx1276]
extends = env:release_cdp
board = ttgo-lora32-v1
lib_deps = nanopb/Nanopb@^0.4.91

[env:prod_ttgo_lora32_v1_3]
extends = env:release_cdp
board = ttgo-lora32-v1
build_flags = 
	${cdp_common.build_flags}
	-DTTGO_1_3
lib_deps = nanopb/Nanopb@^0.4.91

[env:local_heltec_wifi_lora_32_V2]
extends = env:local_cdp
board = heltec_wifi_lora_32_V2
lib_deps = 
	${env:local_cdp.lib_deps}
	https://github.com/ropg/heltec_esp32_lora_v3/archive/refs/tags/v0.9.2.zip
	ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	ropg/HotButton
	h2zero/NimBLE-Arduino@^2.1.0
	nanopb/Nanopb@^0.4.91

[env:local_heltec_wifi_lora_32_V3]
extends = env:local_cdp
board = heltec_wifi_lora_32_V3
build_flags = 
	${env:local_cdp.build_flags}
;	-DDUCK_LANG_EN
lib_deps = 
	${env:local_cdp.lib_deps}
	https://github.com/ropg/heltec_esp32_lora_v3/archive/refs/tags/v0.9.2.zip
	ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	ropg/HotButton
	h2zero/NimBLE-Arduino@^2.1.0
	nanopb/Nanopb@^0.4.91

[env:local_heltec_wifi_lora_32_V4]
extends = env:local_cdp
board = heltec_wifi_lora_32_V4
build_flags = 
	${cdp_common.build_flags}
lib_deps = 
	${env:local_cdp.lib_deps}
	https://github.com/ropg/heltec_esp32_lora_v3/archive/refs/tags/v0.9.2.zip
	ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	ropg/HotButton
	h2zero/NimBLE-Arduino@^2.1.0
	mikalhart/TinyGPSPlus
	nanopb/Nanopb@^0.4.91

[env:local_lilygo_t_beam_sx1262]
extends = env:local_cdp
board = ttgo-t-beam
lib_deps = nanopb/Nanopb@^0.4.91

[env:local_lilygo_t_beam_sx1276]
extends = env:local_cdp
board = ttgo-lora32-v1
lib_deps = nanopb/Nanopb@^0.4.91

[env:local_ttgo_lora32_v1_3]
extends = env:local_cdp
board = ttgo-lora32-v1
lib_deps = 
	${env:local_cdp.lib_deps}
	nanopb/Nanopb@^0.4.91
build_flags = 
	${cdp_common.build_flags}
	-DTTGO_1_3

[env:local_wio_tracker_l1]
board = seeed_wio_tracker_l1
board_build.variants_dir = boards
board_build.ldscript = nrf52840_s140_v7.ld
board_level = pr
extends = nrf52840_base
build_unflags = 
	-std=gnu++11
	-std=gnu++14
	-std=gnu++2a
	-flto
	-fmerge-all-constants
build_flags = 
	${nrf52840_base.build_flags}
	-DSEEED_WIO_TRACKER_L1
	-DLED_BUILTIN=11
	-DNRF52840_XXAA
	-DS140
	-DCFG_DEBUG
	-DSOFTDEVICE_PRESENT
	-DUSE_TINYUSB
	-DENABLE_BLE
;	-DDUCK_LANG_EN
	-std=gnu++17
	-Wno-unused-variable
	-DLOOP_STACK_SZ=2048
	-I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/SPI
	-I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/Wire
	-I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/Adafruit_TinyUSB_Arduino/src
	-I src/platform/nrf52/softdevice
	-I src/platform/nrf52/softdevice/nrf52
upload_protocol = adafruit-nrfutil
upload_flags = 
	--package-version
	4
extra_scripts = 
	pre:tools/example_select.py
	pre:tools/patch_nrf52_weak_handlers.py
	pre:tools/add_variant_libpath.py
	post:tools/gen_uf2.py
lib_ldf_mode = chain+
lib_ignore = 
	ESP Async WebServer
	ESPAsyncTCP
	AsyncTCP
	PubSubClient
lib_extra_dirs = 
	~/.platformio/packages/framework-arduinoadafruitnrf52/libraries
lib_deps = 
	symlink://./
	nanopb/Nanopb@^0.4.91

[env:local_wio_tracker_l1_bletest]
board = seeed_wio_tracker_l1
board_build.variants_dir = boards
board_build.ldscript = nrf52840_s140_v7.ld
board_level = pr
extends = nrf52840_base
build_unflags = 
	-std=gnu++11
	-std=gnu++14
	-std=gnu++2a
build_flags = 
	-DSEEED_WIO_TRACKER_L1
	-DLED_BUILTIN=11
	-DNRF52840_XXAA
	-DS140
	-DCFG_DEBUG
	-DSOFTDEVICE_PRESENT
	-DUSE_TINYUSB
	-DENABLE_BLE
	-std=gnu++17
	-Wno-unused-variable
	-DLOOP_STACK_SZ=2048
	-I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/SPI
	-I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/Wire
	-I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/Adafruit_TinyUSB_Arduino/src
	-I src/platform/nrf52/softdevice
	-I src/platform/nrf52/softdevice/nrf52
upload_protocol = adafruit-nrfutil
upload_flags = 
	--package-version
	4
extra_scripts = 
	pre:tools/example_select.py
	pre:tools/patch_nrf52_weak_handlers.py
	pre:tools/add_variant_libpath.py
	post:tools/gen_uf2.py
lib_ldf_mode = chain+
lib_ignore = 
	ESP Async WebServer
	ESPAsyncTCP
	AsyncTCP
	PubSubClient
lib_extra_dirs = 
	~/.platformio/packages/framework-arduinoadafruitnrf52/libraries
lib_deps = 
	symlink://./
	nanopb/Nanopb@^0.4.91

[env:prod_wio_tracker_l1]
platform = nordicnrf52
framework = arduino
board = seeed_wio_tracker_l1
board_build.variants_dir = boards
board_build.bsp.name = adafruit
platform_packages = 
	framework-arduinoadafruitnrf52 @ https://github.com/meshcore-dev/Adafruit_nRF52_Arduino#d541301
build_unflags = 
	-std=gnu++11
	-std=gnu++14
	-std=gnu++2a
build_flags = 
	${cdp_common.build_flags}
	-DARDUINO_SEEED_WIO_TRACKER_L1
	-std=gnu++17
	-Wno-unused-variable
	-DLOOP_STACK_SZ=8192
extra_scripts = 
	pre:tools/add_variant_libpath.py
lib_deps = 
	mikalhart/TinyGPSPlus
	olikraus/U8g2
	nanopb/Nanopb@^0.4.91

[env:test_heltec_wifi_lora_32_V3]
extends = 
	esp32_base
	cdp_common_test
board = heltec_wifi_lora_32_V3
lib_deps = 
	${esp32_base.lib_deps}
	FS
	WIFI
	nanopb/Nanopb@^0.4.91

[cdp_common_test]
extends = cdp_common
test_build_src = yes
test_filter = test_*
test_framework = unity
build_src_filter = +<./> +<./include> +<./include/boards>
build_flags = 
	${cdp_common.build_flags}
	-std=gnu++20
	-DUNIT_TEST

[cdp_common]
monitor_speed = 115200
monitor_filters = time
lib_deps = 
	WIRE
	SPI
build_flags = 
	-std=gnu++2a
	-Wno-inconsistent-missing-override
	-Wno-missing-field-initializers
	-Wno-format
	-I ./src
	-I ./src/include
	-I ./src/include/boards
	-DRADIOLIB_EXCLUDE_CC1101
	-DRADIOLIB_EXCLUDE_NRF24
	-DRADIOLIB_EXCLUDE_RF69
	-DRADIOLIB_EXCLUDE_SX1231
	-DRADIOLIB_EXCLUDE_SX1233
	-DRADIOLIB_EXCLUDE_SX128X
	-DRADIOLIB_EXCLUDE_SI443X
	-DRADIOLIB_EXCLUDE_RFM2X
	-DRADIOLIB_EXCLUDE_AFSK
	-DRADIOLIB_EXCLUDE_BELL
	-DRADIOLIB_EXCLUDE_HELLSCHREIBER
	-DRADIOLIB_EXCLUDE_MORSE
	-DRADIOLIB_EXCLUDE_RTTY
	-DRADIOLIB_EXCLUDE_SSTV
	-DRADIOLIB_EXCLUDE_AX25
	-DRADIOLIB_EXCLUDE_DIRECT_RECEIVE
	-DRADIOLIB_EXCLUDE_PAGER
	-DRADIOLIB_EXCLUDE_FSK4
	-DRADIOLIB_EXCLUDE_APRS
	-DRADIOLIB_EXCLUDE_LLCC68
	-D CDP_INFO
build_unflags = 
	-std=gnu++11
