

#define CDPCFG_RADIO_SX126X
#define CDPCFG_LORA_CLASS SX1262

#define CDPCFG_PIN_LORA_CS 10
#define CDPCFG_PIN_LORA_DIO0 9 // BUSY PIN
#define CDPCFG_PIN_LORA_DIO1 8
#define CDPCFG_PIN_LORA_DIO2 -1
#define CDPCFG_PIN_LORA_RST 14


#define CDPCFG_PIN_LORA_BUSY CDPCFG_PIN_LORA_DIO0

// OLED display settings
#define CDPCFG_OLED_NONE

// WiFi module
#define CDPCFG_WIFI_NONE
