
#define CDPCFG_RADIO_SX126X
#define CDPCFG_LORA_CLASS SX1262

#define CDPCFG_PIN_LORA_CS 10
#define CDPCFG_PIN_LORA_DIO0 9 // BUSY PIN
#define CDPCFG_PIN_LORA_DIO1 8
#define CDPCFG_PIN_LORA_DIO2 -1
#define CDPCFG_PIN_LORA_RST 14

#define CDPCFG_PIN_LORA_BUSY CDPCFG_PIN_LORA_DIO0

// OLED display settings
#ifdef ENABLE_DISPLAY
#define CDPCFG_PIN_OLED_CLOCK 15
#define CDPCFG_PIN_OLED_DATA 4
#define CDPCFG_PIN_OLED_RESET 16
#else
#define CDPCFG_OLED_NONE
#endif

// WiFi module
#define CDPCFG_WIFI_NONE
