

#define CDPCFG_RADIO_SX126X
#define CDPCFG_LORA_CLASS SX1262

#define CDPCFG_RADIO_SX126X
#define CDPCFG_LORA_CLASS SX1262

#define CDPCFG_PIN_LORA_CS 35
#define CDPCFG_PIN_LORA_DIO0 39 
#define CDPCFG_PIN_LORA_BUSY CDPCFG_PIN_LORA_DIO0

#define CDPCFG_PIN_LORA_DIO1 38
#define CDPCFG_PIN_LORA_DIO2 -1
#define CDPCFG_PIN_LORA_RST 47

// OLED display settings
#define CDPCFG_OLED_NONE

// WiFi module
#define CDPCFG_WIFI_NONE
