#ifndef DUCKERROR_H
#define DUCKERROR_H

#define DUCK_ERR_NONE 0

#define DUCKLORA_ERR_NONE DUCK_ERR_NONE

#define DUCKLORA_ERR_BEGIN          -1000
#define DUCKLORA_ERR_SETUP          -1001
#define DUCKLORA_ERR_RECEIVE        -1002
#define DUCKLORA_ERR_TIMEOUT        -1003
#define DUCKLORA_ERR_TRANSMIT       -1004
#define DUCKLORA_ERR_HANDLE_PACKET  -1050
#define DUCKLORA_ERR_MSG_TOO_LARGE  -1051
#define DUCKLORA_ERR_MSG_EMPTY      -1052

#define DUCKWIFI_ERR_NOT_AVAILABLE  -2000
#define DUCKWIFI_ERR_DISCONNECTED   -2001

#define  DUCKDNS_ERR_STARTING       -3000


#endif